# Generated by Django 5.0.3 on 2024-05-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ManyToManyField(related_name='produc', to='app.category'),
        ),
    ]
