# Generated by Django 5.0.3 on 2024-05-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
